name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        env:
          TARGET_VM_ADDRESS: your_vm_address
          TARGET_VM_USERNAME: your_vm_username
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem $TARGET_VM_USERNAME@$TARGET_VM_ADDRESS 'bash -s' < script/deploy.sh


## semuanya hanyak fake script tanpa id_rsa sebenarnya, begitu juga dengan vm address menyesuaikan dengan target VM
